---
# tasks file for splunk forwarder-installation
- name: add splunk user group to system
  group:
    name: "{{ splunk_uf_system_group }}"
    state: present

- name: add splunk user
  user:
    name: "{{ splunk_uf_system_user }}"
    group: "{{ splunk_uf_system_group }}"
    comment: "Splunk service user"
    shell: /usr/sbin/nologin    # Why this script

- name: install splunk forwarder binary from remote url
  unarchive:
    src: "{{ jfrog_url_linux_forwarder }}"
    dest: /opt
    remote_src: yes
    creates: /opt/splunkforwarder
    owner: "{{ splunk_uf_system_user }}"
    group: "{{ splunk_uf_system_group }}"

- name: accept license and start splunk forwarder
  shell: /opt/splunkforwarder/bin/splunk start --answer-yes --no-prompt --accept-license
  args:
    executable: /bin/sh
  become_user: "{{ splunk_uf_system_user }}"
  
- name: enable boot-start
  shell: "/opt/splunkforwarder/bin/splunk enable boot-start -user {{ splunk_uf_system_user}}"
  #when: splunk_uf_start_on_boot|bool
  become: yes

- name: install inputs.conf for webserver
  template:
    src: "inputs/inputs-{{ type }}.conf.j2"
    dest: /opt/splunkforwarder/etc/system/local/inputs.conf
    owner: "{{ splunk_uf_system_user }}"
    group: "{{ splunk_uf_system_group }}"
    backup: yes
    mode: 0644
  #when: splunk_liberty_webserver_inputs_conf_template | default(false)
  notify:
    - restart splunkforwarder

- name: install outputs.conf for app server
  template:
    src: "{{ splunk_liberty_appserver_outputs_conf_template }}"
    dest: /opt/splunkforwarder/etc/system/local/outputs.conf
    owner: "{{ splunk_uf_system_user }}"
    group: "{{ splunk_uf_system_group }}"
    backup: yes
    mode: 0644
  #when: splunk_liberty_appserver_outputs_conf_template | default(false)
  notify:
    - restart splunkforwarder
    
