#Default value for the Required parameters

#artifactory Binary URL's
jfrog_url_linux_forwarder: "{{ jfrog_url }}/{{ splunk_lin }}" 
jfrog_url: "https://fbbd1.fb/artifactory/devops-local/downloads/splunk-forwarders"
splunk_lin: splunkforwarder-7.2.6-c0bf0f679ce9-Linux-x86_64.tgz

#Splunk user details
splunk_uf_system_user: splunk
splunk_uf_system_group: "{{ splunk_uf_system_user }}"

# Splunk forwarder enterprise URl: This value will render in the output.conf
#splunk_forwarder_enterprise: "splunk-enterprise:(port num of splunk enterprise)"
splunk_forwarder_indexer: "splunk-indexer:9997" #Splunk URl

#On boot Yes
splunk_uf_start_on_boot: yes
# Vars only if boot strap module is used.
splunk_forwarder_sourcetype: "default" # Can be any type like nginx and etc...
splunk_forwarder_index: "default"  # dont know when, why use it and how to change it


#input and output.conf file variables for liberty app server
splunk_liberty_appserver_inputs_conf_template: libertyappserver-conf/inputs.conf.j2
splunk_liberty_appserver_outputs_conf_template: libertyappserver-conf/output.conf.j2

#input and output.conf file variables for liberty web server
splunk_liberty_webserver_inputs_conf_template: libertywebserver-conf/inputs.conf.j2
splunk_liberty_webserver_outputs_conf_template: libertywebserver-conf/output.conf.j2


# Configuration for inputs.conf
# ---
splunk_webserver_inputs_conf_template: libertyappserver-conf/inputs.conf.j2
# Input attributes below are all optional
#Host file like Splunk URL

#forwarder Logs Details
splunk_forwarder_appserver_logs: |
  [monitor:///opt/wlp/logs/.../*.log]

splunk_forwarder_webserver_logs: |
  [monitor:///opt/logs/.../access*]
  [monitor:///opt/logs/.../error*]
  [monitor:///opt/logs/.../http_plugin.log]
  [monitor:///opt/WebSphereV7-efirstbank-443-*/Plugins/logs/efirstbank-443-*-server1*/http_plugin.log]
